#!/usr/bin/env bash

# edit config files
alias vialias='vim $ALIASES_FILE'
alias vizshenv='vim $ZSHENV_FILE'
alias vizshrc='vim $ZSHRC_FILE' 
alias vizprofile='vim $ZPROFILE_FILE'
alias vibashrc='vim $BASHRC_FILE'
alias vitmux='vim $TMUX_CONF_FILE'
alias vivimrc='vim $VIMRC_FILE'
alias vissh='vim $SSH_CONFIG_FILE'
alias viprofile='vim $LOCAL_PROFILE_FILE'

# Commands
alias ls='ls --color=auto'
alias lsl='ls -l'
alias ll='ls -lahF'
alias lls='ls -lahFtr'
alias la='ls -A'
alias l='ls -CF'

# Utility
alias pg='ping 8.8.8.8'

# Vim-like split commands for tmux
alias split='tmux split-window'  
alias vsplit='tmux split-window -h'
