#!/usr/bin/env zsh

# Load aliases
source $ALIASES_FILE

# History
export HISTFILE="$ZHISTORY_FILE"
export HISTSIZE=10000
export SAVEHIST=10000

setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

# Settings for Oh-My-Zsh
ZSH_THEME="robbyrussell"

# plugins for MacOS
if [[ `uname` == "Darwin" ]]; then
    ZSH_TMUX_CONFIG=$TMUX_CONF_FILE
    ZSH_TMUX_AUTOSTART=true
    plugins=(git macos brew rust tmux)
fi
source $ZSH_DOT_DIR/oh-my-zsh/oh-my-zsh.sh

# Compilation flags
ARCHFLAGS="-arm64"

# Laod fzf
source $FZF_ZSH_FILE
